// Copyright © yanghy. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package codegen

// lcl 自动代码模板
const LCLAutoCodeTemplate = `// ==============================================================================
// Code generated by ENERGY GUI Designer; DO NOT EDIT.
// ==============================================================================
// Designer: {{.BaseInfo.DesignerVersion}}
// DateTime: {{.BaseInfo.DateTime}}
// Layout: {{.BaseInfo.UIFile}}
// User: {{.BaseInfo.UserFile}}
// ==============================================================================

{{$Form := .}}

package {{$Form.PackageName}}

import (
	{{$Form.GoGetImports}}
)

type T{{$Form.Form.Name}}UI struct {
	lcl.TEngForm
	{{range $Form.Form.Children -}}
	{{.GoFieldName}} {{.GoIntfName}}
	{{end -}}
}

var {{$Form.Form.Name}} T{{$Form.Form.Name}}

// FormCreate Form creation event. Automatic call
func (m *T{{$Form.Form.Name}}) FormCreate(sender lcl.IObject) {
	{{$formComp := $Form.Form}}
	{{- range $propIndex, $prop := $formComp.Properties -}}
		{{with $prop.GoPropertySet $formComp $Form -}}
			{{.}}
		{{end -}}
	{{end -}}
	m.initComponents()
	lcl.CallFormCreate(m, sender)
}

// Initialize component
func (m *T{{$Form.Form.Name}}) initComponents() {
	{{range $compIndex, $comp := $Form.Form.Children -}}
		{{$comp.GoNewObject}}
	{{- range $propIndex, $prop := $comp.Properties -}}
		{{with $prop.GoPropertySet $comp $Form -}}
			{{.}}
		{{end -}}
	{{end -}}
		{{$comp.GoSetObjectParent}}
	{{end -}}
}
`
