// Copyright © yanghy. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package project

const ResourcesGoTemplate = `// ==============================================================================
// embedded resource
// ==============================================================================

package resources

import (
	"embed"
	"github.com/energye/lcl/emfs"
	"github.com/energye/lcl/lcl"
)

//go:embed embed
var icon embed.FS

// Embed Get embedded resources
// Function signature cannot be modified
func Embed(fileName string) []byte {
	data, _ := icon.ReadFile("embed/" + fileName)
	return data
}

// SetIcon Set application icon
// Function signature cannot be modified
func SetIcon() {
	stream := lcl.NewMemoryStream()
	lcl.StreamHelper.Write(stream, Embed("icon.png"))
	stream.SetPosition(0)
	png := lcl.NewPortableNetworkGraphic()
	png.LoadFromStreamWithStream(stream)
	lcl.Application.Icon().Assign(png)
	png.Free()
	stream.Free()
}

func init() {
	emfs.RegisterEmbedFS(emfs.FSName, icon)
	lcl.SetOnBeforeRun(SetIcon)
}
`

const AppCodeTemplate = `// ==============================================================================
// Code generated by ENERGY GUI Designer; DO NOT EDIT.
// Application auto configuration form maintenance list
// ==============================================================================

package {{.Package}}

import (
	"github.com/energye/energy/v3/application/pack"
	"github.com/energye/lcl/api/libname"
	"github.com/energye/lcl/lcl"
	"runtime"
)

var (
	// Info app pack info
	Info = pack.Info
)

// Forms form maintenance list
var Forms = []lcl.IEngForm{
	{{.GoFormNames}}
}

func init() {
	if runtime.GOOS == "linux" {
		libname.UseWS = "{{.LinuxWS}}"
	}
	if runtime.GOOS == "darwin" {
		libname.EnableUniversalBinary = {{.BuildOption.MacCommonLib}}
	}
}
`

const GoModTemplate = `module {{.Name}}

go 1.20

{{.Data}}
`

const ResourcesWindowsGoTemplate = `// ==============================================================================
// Application Metadata
// ==============================================================================

//go:build windows

package resources

import _ "{{.Name}}/resources/metadata"
`

const MetadataWindowsGoTemplate = `//go:build windows

package metadata
`

const RunLCLCodeTemplate = `// ==============================================================================
// Application startup portal
// ==============================================================================

package main

import (
	"github.com/energye/lcl/lcl"
	"{{.Name}}/app"
	_ "{{.Name}}/resources"
)

func main() {
	// Global Initialization
	lcl.Init()
	// Start application message loop
	lcl.Run(app.Forms...)
}
`

const RunWVCodeTemplate = `// ==============================================================================
// Application startup portal
// ==============================================================================

package main

import (
	"embed"
	"github.com/energye/energy/v3/application"
	"github.com/energye/energy/v3/ipc"
	"github.com/energye/energy/v3/wv"
	"{{.Name}}/app"
	_ "{{.Name}}/resources"
)

//go:embed web
var web embed.FS

func main() {
	// Global Initialization
	wvApp := wv.Init()
	wvApp.SetOptions(application.Options{
		DefaultURL: "fs://energy/index.html",
	})
	// Local resource loading
	wvApp.SetLocalLoad(application.LocalLoad{
		Scheme:     "fs",
		Domain:     "energy",
		ResRootDir: "web",
		FS:         web,
	})
	// IPC
	ipc.On("counter:change", func(context ipc.IContext) {
		data := context.Data().([]any)
		context.Result(data[0])
	})
	wv.Run(app.Forms...)
}
`

const WebIndexHTMLTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ENERGY</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{--webkit-app-region: drag;font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;height:100vh;background:#0f0f13;color:#e4e4e7;display:flex;align-items:center;justify-content:center;overflow:hidden}
.hero{display:flex;flex-direction:column;align-items:center;text-align:center;padding:0 20px;position:relative}
.hero::before{content:'';position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:400px;height:400px;background:radial-gradient(circle,rgba(99,102,241,.15) 0%,transparent 70%);pointer-events:none}
.logo{font-size:1.8rem;font-weight:800;letter-spacing:-.02em;background:linear-gradient(135deg,#818cf8,#6ee7b7);-webkit-background-clip:text;-webkit-text-fill-color:transparent;line-height:1.1}
.tagline{font-size:.78rem;color:#71717a;margin-top:5px;max-width:440px;line-height:1.4}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;width:100%;max-width:480px;margin:14px 0}
.card,.demo{background:#18181b;border:1px solid #27272a}
.card{border-radius:8px;padding:10px 12px;transition:border-color .2s;text-align:left}
.card:hover{border-color:#3f3f46}
.card h3,.demo-label,.hint{font-size:.68rem;text-transform:uppercase;letter-spacing:.05em}
.card h3{font-weight:600;color:#a1a1aa;margin-bottom:2px}
.card p{font-size:.72rem;color:#d4d4d8;line-height:1.4}
.demo{border-radius:10px;padding:12px 24px;display:flex;align-items:center;gap:16px}
.demo-label{color:#52525b;letter-spacing:.07em;white-space:nowrap}
#count{font-size:1.2rem;font-weight:700;color:#e4e4e7;background:none;border:none;cursor:pointer;padding:2px 12px;border-radius:6px;transition:background .15s;white-space:nowrap}
#count:hover{background:#27272a}
#count:active{transform:scale(.97)}
.hint,footer{color:#3f3f46}
.hint{white-space:nowrap}
footer{position:absolute;bottom:8px;left:0;right:0;text-align:center;font-size:.65rem}
footer a{color:#6366f1;text-decoration:none}
footer a:hover{text-decoration:underline}
</style>
</head>
<body>
<section class="hero">
<div class="logo">ENERGY</div>
<p class="tagline">Cross-platform desktop framework - Native, Webview, CEF rendering & self-bootstrapping GUI Designer</p>
<div class="grid">
<div class="card"><h3>Native UI</h3><p>System-native widgets for max performance and platform fidelity</p></div>
<div class="card"><h3>Webview & CEF</h3><p>System Webview and Chromium embedded for flexible web-based UI</p></div>
<div class="card"><h3>Cross-Platform</h3><p>Windows, macOS and Linux from one Go codebase</p></div>
<div class="card"><h3>GUI Designer</h3><p>Visual editor built with the framework itself - self-bootstrapping</p></div>
</div>
<div class="demo">
<span class="demo-label">IPC Demo</span>
<button id="count" onclick="doCount()">Count: 0</button>
<span class="hint">Go backend to Web frontend via IPC</span>
</div>
</section>
<footer>Powered by <a href="https://github.com/energye/energy">ENERGY</a> &middot; Go + WebView</footer>
<script>
let n=0;
function doCount(){
  ipc.emit('counter:change',[++n],function(r){
    document.getElementById('count').textContent='Count: '+r
  })
}
</script>
</body>
</html>
`
