package codegen

// autoCodeTemplate 自动代码模板
const autoCodeTemplate = `// ==============================================================================
// 🔥 Code automatically generated by ENERGY GUI Designer. DO NOT EDIT
// 🔥 ENERGY GUI 设计器自动生成代码. 不能编辑
// ==============================================================================
// 🔍 基本信息
//     生成工具: ENERGY GUI Designer v1.2.0
//     生成时间: 2025-10-31 15:30:45
//     设计文件: form1.ui
//     用户文件: form1.go
//     功能描述: 基于ENERGY GUI框架的实现, 包含UI组件创建
// ==============================================================================

package {{.PackageName}}

import (
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
)

type {{.FormName}} struct {
	lcl.TEngForm
	{{range .Components}}{{.Name}} lcl.{{.ClassName}}
	{{end}}
} 

// FormCreate 窗体创建接口实现. 自动调用
func (m *{{.FormName}}) FormCreate(sender lcl.IObject) {
	// 设置窗体属性
	{{range .Properties}} m.Set{{.Name}}({{.Value}})
	{{end}}
	// 初始化组件
	m.initComponents()
    // 调用用户创建窗体事件
	m.OnFormCreate(sender)
}

// initComponents 初始化组件
func (m *{{.FormName}}) initComponents() {
	{{range .Components}} m.{{.Name}} = lcl.New{{.ClassName}}(m)
	{{end}}
}
`

// userCodeTemplate 用户代码模板
const userCodeTemplate = `// ==============================================================================
// 📚 Form1 用户代码文件
// 📌 该文件不存在时自动创建
// ✏️ 可在此文件中添加事件处理和业务逻辑
// ==============================================================================

package {{.PackageName}}

import (
	"github.com/energye/lcl/lcl"
)

// OnFormCreate 窗体初始化事件
func (m *{{.FormName}}) OnFormCreate(sender lcl.IObject) {
	// 在此处添加窗体初始化代码
}

{{range .Components}}
// On{{.Name}}Click {{.Name}}点击事件
func (m *{{.FormName}}) On{{.Name}}Click(sender lcl.IObject) {
	// 在此处添加{{.Name}}点击事件处理代码
}
{{end}}
`

// main 文件代码模板
// main.go 不存在项目目录时创建
const mainCodeTemplate = `// ==============================================================================
// 📚 main 应用启动入口文件
// 📌 该文件不存在时自动创建
// ✏️ 可在此文件中添加业务逻辑
// ==============================================================================

package main

import (
	"github.com/energye/lcl/lcl"
)

func main() {
	lcl.Init(nil, nil)
	lcl.Application.Initialize()
	lcl.Application.SetMainFormOnTaskBar(true)
	lcl.Application.SetScaled(true)
	lcl.Application.NewForms(&MainForm, &Form1)
	lcl.Application.Run()
}
`
