package codegen

// lcl 自动代码模板
const lclAutoCodeTemplate = `// ==============================================================================
// Code generated by ENERGY GUI Designer; DO NOT EDIT.
// ==============================================================================
// Designer: {{.BaseInfo.DesignerVersion}}
// DateTime: {{.BaseInfo.DateTime}}
// Layout: {{.BaseInfo.UIFile}}
// User: {{.BaseInfo.UserFile}}
// ==============================================================================

{{$Form := .}}

package {{$Form.PackageName}}

import (
	{{$Form.GoGetImports}}
)

type T{{$Form.Form.Name}}UI struct {
	lcl.TEngForm
	{{range $Form.Form.Children -}}
	{{.GoFieldName}} {{.GoIntfName}}
	{{end -}}
}

var {{$Form.Form.Name}} T{{$Form.Form.Name}}

// FormCreate Form creation event. Automatic call
func (m *T{{$Form.Form.Name}}) FormCreate(sender lcl.IObject) {
	{{$formComp := $Form.Form}}
	{{- range $propIndex, $prop := $formComp.Properties -}}
		{{with $prop.GoPropertySet $formComp $Form -}}
			{{.}}
		{{end -}}
	{{end -}}
	m.initComponents()
	lcl.CallFormCreate(m, sender)
}

// Initialize component
func (m *T{{$Form.Form.Name}}) initComponents() {
	{{range $compIndex, $comp := $Form.Form.Children -}}
		{{$comp.GoNewObject}}
	{{- range $propIndex, $prop := $comp.Properties -}}
		{{with $prop.GoPropertySet $comp $Form -}}
			{{.}}
		{{end -}}
	{{end -}}
		{{$comp.GoSetObjectParent}}
	{{end -}}
}
`
