// Copyright © yanghy. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package options

// resources/resources.go
// 资源代码模板
const resourcesGoTemplate = `// ==============================================================================
// embedded resource
// ==============================================================================

package resources

import (
	"embed"
	"github.com/energye/lcl/emfs"
	"github.com/energye/lcl/lcl"
)

//go:embed embed
var icon embed.FS

// Embed Get embedded resources
// Function signature cannot be modified
func Embed(fileName string) []byte {
	data, _ := icon.ReadFile("embed/" + fileName)
	return data
}

// SetIcon Set application icon
// Function signature cannot be modified
func SetIcon() {
	stream := lcl.NewMemoryStream()
	lcl.StreamHelper.Write(stream, Embed("icon.png"))
	stream.SetPosition(0)
	png := lcl.NewPortableNetworkGraphic()
	png.LoadFromStreamWithStream(stream)
	lcl.Application.Icon().Assign(png)
	png.Free()
	stream.Free()
}

func init() {
	emfs.RegisterEmbedFS(emfs.FSName, icon)
	lcl.SetOnBeforeRun(SetIcon)
}
`

// app.go 文件代码模板
// 用于提供 main.go NewForms 参数使用
// 在项目窗体创建/更新时同步修改
const appCodeTemplate = `// ==============================================================================
// Code generated by ENERGY GUI Designer; DO NOT EDIT.
// Application auto configuration form maintenance list
// ==============================================================================

package {{.Package}}

import (
	"github.com/energye/energy/v3/application/pack"
	"github.com/energye/lcl/api/libname"
	"github.com/energye/lcl/lcl"
	"runtime"
)

var (
	// Info app pack info
	Info = pack.Info
)

// Forms form maintenance list
var Forms = []lcl.IEngForm{
	{{.GoFormNames}}
}

func init() {
	if runtime.GOOS == "linux" {
		libname.UseWS = "{{.LinuxWS}}"
	}
	if runtime.GOOS == "darwin" {
		libname.EnableUniversalBinary = {{.BuildOption.MacCommonLib}}
	}
}
`

// go.mod 模块文件模板
const goModTemplate = `module {{.Name}}

go 1.20

{{.Data}}
`

// resources/metadata_windows.go
// 资源代码模板
const resourcesWindowsGoTemplate = `// ==============================================================================
// Application Metadata
// ==============================================================================

//go:build windows

package resources

import _ "{{.Name}}/resources/metadata"
`

// resources/metadata/metadata_windows.go
// 资源代码模板
const metadataWindowsGoTemplate = `//go:build windows

package metadata
`
