// ==============================================================================
// Code generated by ENERGY GUI Designer; DO NOT EDIT.
// Application auto configuration form maintenance list
// ==============================================================================

package designer

import (
	"github.com/energye/energy/v3/application/pack"
	"github.com/energye/lcl/api/libname"
	"github.com/energye/lcl/lcl"
	"runtime"
)

var (
	// Info app pack info
	Info = pack.Info
)

// Forms form maintenance list
var Forms = []lcl.IEngForm{
	
}

func init() {
	if runtime.GOOS == "linux" {
		libname.UseWS = "gtk3"
	}
	if runtime.GOOS == "darwin" {
		libname.EnableUniversalBinary = false
	}
}
